import 'package:customer/inAppPages/food/Food.dart';
import 'package:customer/loginAndSignUpPages/loginSignUp/firstPage.dart';
import 'package:flutter/animation.dart';

class Fake{

   static Food a = new Food(name:"hot dog",restaurantName:"arman_restaurant",picture:"https://upload.wikimedia.org/wikipedia/commons/b/b1/Hot_dog_with_mustard.png",restaurantAvatar:"https://media-cdn.tripadvisor.com/media/photo-s/1b/67/cc/f8/chestnut-restaurant.jpg",price: 12000,Process: false,active: false);
   static Food b = new Food(name:"hamburger",restaurantName:"amir_restaurant",picture:"https://assets.epicurious.com/photos/57c5c6d9cf9e9ad43de2d96e/master/pass/the-ultimate-hamburger.jpg",restaurantAvatar:"https://cdn1.vectorstock.com/i/1000x1000/81/30/fast-food-restaurant-and-vector-10328130.jpg",price: 15000,Process: false,active: false);
  static  Food c = new Food(name: "pizza",restaurantName: "rabin_restaurant",picture: "https://www.aislac.org/wp-content/uploads/2021/01/pizza.jpg",restaurantAvatar: "https://cdn1.vectorstock.com/i/1000x1000/33/80/fast-food-shop-store-front-flat-style-vector-9183380.jpg",price: 20000,Process: false,active: false);
   static Food d = new Food(name: "french fries",restaurantName: "arman_restaurant",picture: "https://shoolenco.com/en/wp-content/uploads/sites/4/2018/09/french-fries88.jpg",restaurantAvatar:"https://media-cdn.tripadvisor.com/media/photo-s/1b/67/cc/f8/chestnut-restaurant.jpg",price: 10000,Process: false,active: false );
  static  Food e = new Food(name: "chicken",restaurantName: "amir_restaurant",picture: "https://www.seriouseats.com/thmb/hGmf-CklPEWYtGrsB1XIOfldngM=/1500x844/smart/filters:no_upscale()/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2015__07__20210324-SouthernFriedChicken-Andrew-Janjigian-21-cea1fe39234844638018b15259cabdc2.jpg",restaurantAvatar:"https://cdn1.vectorstock.com/i/1000x1000/81/30/fast-food-restaurant-and-vector-10328130.jpg",price: 30000,Process: false,active: false);
  static  Food f = new Food(name: "pop corn",restaurantName: "rabin_restaurant",picture: "https://www.rachelpaulsfood.com/wp-content/uploads/DSC_0697.jpg",restaurantAvatar: "https://cdn1.vectorstock.com/i/1000x1000/33/80/fast-food-shop-store-front-flat-style-vector-9183380.jpg",price: 3000,Process: false,active: false);
   static Food g = new Food(name : "kebab" , restaurantName: "arman_restaurant",picture: "https://media.mehrnews.com/d/2019/07/09/4/3175131.jpg",restaurantAvatar: "https://media-cdn.tripadvisor.com/media/photo-s/1b/67/cc/f8/chestnut-restaurant.jpg",price: 17000,Process: false,active: false);
}